name: Sum Two Numbers new

on:
  workflow_dispatch:
    inputs:
      numbers_json:
        description: 'JSON input'
        required: true
        default: '{"num1":0,"num2":0}'

  schedule:
    - cron: "30 0 * * *"   # 6:00 AM IST

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Workflow is alive"
